'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { formatCurrency } from '@/lib/format'

const inputClass =
  'w-full rounded-lg border border-border-subtle px-3 py-2 text-sm outline-none focus:border-brand-gold'
const labelClass = 'mb-1 block text-xs font-semibold uppercase tracking-wide text-text-muted'

/**
 * Opens a GST filing for a month. output_gst / input_gst may be left blank — the server
 * pre-sums them from the period's invoices and purchase bills when omitted. net_payable
 * (output − input) is generated by the DB; the preview here is informational only.
 *
 * `month` input yields 'YYYY-MM', exactly the period format the schema expects.
 */
export function GstFilingForm() {
  const router = useRouter()
  const [period, setPeriod] = useState('')
  const [output, setOutput] = useState('')
  const [input, setInput] = useState('')
  const [pending, setPending] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const netPreview = (Number(output) || 0) - (Number(input) || 0)
  const hasFigures = output !== '' || input !== ''

  async function save() {
    if (!period) return setError('Pick the filing month.')

    setPending(true)
    setError(null)

    const res = await fetch('/api/tax/gst', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        period,
        output_gst: output === '' ? null : Number(output),
        input_gst: input === '' ? null : Number(input),
      }),
    })

    const body = await res.json().catch(() => ({}))
    setPending(false)
    if (!res.ok) {
      setError(body.error ?? 'Could not open the filing.')
      return
    }
    setOutput('')
    setInput('')
    router.refresh()
  }

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <div>
          <label htmlFor="gst-period" className={labelClass}>
            Period (month)
          </label>
          <input
            id="gst-period"
            type="month"
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="gst-output" className={labelClass}>
            Output GST
          </label>
          <input
            id="gst-output"
            type="number"
            min="0"
            step="0.01"
            value={output}
            onChange={(e) => setOutput(e.target.value)}
            placeholder="Auto from invoices"
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="gst-input" className={labelClass}>
            Input GST
          </label>
          <input
            id="gst-input"
            type="number"
            min="0"
            step="0.01"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Auto from bills"
            className={inputClass}
          />
        </div>
      </div>

      {hasFigures && (
        <div className="rounded-lg border border-border-subtle bg-surface-bg px-4 py-3">
          <div className="flex items-center justify-between text-sm">
            <span className="text-text-muted">Net payable (generated: output − input)</span>
            <span className="font-semibold text-brand-slate">{formatCurrency(netPreview)}</span>
          </div>
        </div>
      )}

      <p className="text-xs text-text-muted">
        Leave the amounts blank to have the system sum them from this month&apos;s invoices and
        bills. You can adjust them before marking the filing as filed.
      </p>

      {error && <p className="text-xs text-status-danger">⚠ {error}</p>}

      <button
        onClick={save}
        disabled={pending}
        className="rounded-lg bg-brand-gold px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-brand-orange disabled:opacity-60"
      >
        {pending ? 'Opening…' : 'Open filing'}
      </button>
    </div>
  )
}
