'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { formatCurrency } from '@/lib/format'

const inputClass =
  'w-full rounded-lg border border-border-subtle px-3 py-2 text-sm outline-none focus:border-brand-gold'
const labelClass = 'mb-1 block text-xs font-semibold uppercase tracking-wide text-text-muted'

export interface PoOption {
  id: string
  po_number: string
  vendor_name: string | null
  total_amount: number
}

/**
 * Records a vendor bill — the payables entry point. Purchase ORDERS belong to Distribution
 * (0007); Finance can bill against an existing PO (pre-fills vendor + amount from it) or
 * record a standalone bill. total_amount is generated by the DB from amount + GST, previewed
 * here but never sent. recorded_by is the session user, set server-side.
 */
export function PurchaseBillForm({ purchaseOrders = [] }: { purchaseOrders?: PoOption[] }) {
  const router = useRouter()
  const [poId, setPoId] = useState<string | null>(null)
  const [vendorName, setVendorName] = useState('')
  const [billNumber, setBillNumber] = useState('')
  const [amount, setAmount] = useState('')
  const [gst, setGst] = useState('')
  const [dueDate, setDueDate] = useState('')
  const [pending, setPending] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const total = (Number(amount) || 0) + (Number(gst) || 0)

  function applyPo(value: string) {
    if (!value) {
      setPoId(null)
      return
    }
    const po = purchaseOrders.find((p) => p.id === value)
    if (!po) return
    setPoId(po.id)
    if (po.vendor_name) setVendorName(po.vendor_name)
    if (po.total_amount) setAmount(String(po.total_amount))
  }

  async function save() {
    if (vendorName.trim().length < 1) return setError('Enter a vendor name.')
    if ((Number(amount) || 0) <= 0) return setError('Enter an amount greater than zero.')

    setPending(true)
    setError(null)

    const res = await fetch('/api/purchase-bills', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        purchase_order_id: poId,
        vendor_name: vendorName.trim(),
        bill_number: billNumber.trim() || null,
        amount: Number(amount),
        gst_amount: Number(gst) || 0,
        due_date: dueDate || null,
      }),
    })

    const body = await res.json().catch(() => ({}))
    setPending(false)
    if (!res.ok) {
      setError(body.error ?? 'Could not record the bill.')
      return
    }
    router.push('/finance/purchases')
    router.refresh()
  }

  return (
    <div className="space-y-4">
      {purchaseOrders.length > 0 && (
        <div>
          <label htmlFor="bill-po" className={labelClass}>
            Against a purchase order
          </label>
          <select id="bill-po" onChange={(e) => applyPo(e.target.value)} className={inputClass}>
            <option value="">Standalone bill (no PO)…</option>
            {purchaseOrders.map((p) => (
              <option key={p.id} value={p.id}>
                {p.po_number} · {p.vendor_name ?? 'Vendor'} · {formatCurrency(p.total_amount)}
              </option>
            ))}
          </select>
          <p className="mt-1 text-xs text-text-muted">
            Purchase orders are raised by Distribution. Billing against one links the two.
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <label htmlFor="bill-vendor" className={labelClass}>
            Vendor name
          </label>
          <input
            id="bill-vendor"
            value={vendorName}
            onChange={(e) => setVendorName(e.target.value)}
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="bill-number" className={labelClass}>
            Bill number
          </label>
          <input
            id="bill-number"
            value={billNumber}
            onChange={(e) => setBillNumber(e.target.value)}
            placeholder="Vendor's bill no. (optional)"
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="bill-amount" className={labelClass}>
            Amount (excl. GST)
          </label>
          <input
            id="bill-amount"
            type="number"
            min="0"
            step="0.01"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="bill-gst" className={labelClass}>
            GST amount
          </label>
          <input
            id="bill-gst"
            type="number"
            min="0"
            step="0.01"
            value={gst}
            onChange={(e) => setGst(e.target.value)}
            className={inputClass}
          />
        </div>
        <div>
          <label htmlFor="bill-due" className={labelClass}>
            Due date
          </label>
          <input
            id="bill-due"
            type="date"
            value={dueDate}
            onChange={(e) => setDueDate(e.target.value)}
            className={inputClass}
          />
        </div>
      </div>

      <div className="rounded-lg border border-border-subtle bg-surface-bg px-4 py-3">
        <div className="flex items-center justify-between text-sm">
          <span className="text-text-muted">Total (generated by the system)</span>
          <span className="font-semibold text-brand-slate">{formatCurrency(total)}</span>
        </div>
      </div>

      {error && <p className="text-xs text-status-danger">⚠ {error}</p>}

      <button
        onClick={save}
        disabled={pending}
        className="rounded-lg bg-brand-gold px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-brand-orange disabled:opacity-60"
      >
        {pending ? 'Recording…' : 'Record bill'}
      </button>
    </div>
  )
}
