-- Solar Pulse OS — Distribution Module
-- Migration 0007: vendors, purchase orders, dispatches, allocations, returns
--
-- Builds on 0001/0002/0005. Reuses organizations / departments / roles / users /
-- audit_logs / leads and the set_updated_at() trigger function, plus the
-- auth_is_ceo() / auth_org_id() helpers — none of those are redefined here.
--
-- Security model is TWO tiers, not three: material movement is a shared
-- department operation, so every Distribution member sees every PO, dispatch,
-- allocation, and return. There is deliberately no per-employee ownership tier
-- like Sales has — a dispatch is not personal pipeline data.
--
-- The one place this module's permissions are not a flat two-tier pattern is the
-- Finance approval gate on purchase orders. Distribution may prepare a PO and
-- act on it once approved, but may not approve it themselves. That is enforced
-- three ways, deliberately redundant:
--   1. the service layer's transition table (clear 400s),
--   2. the narrowed Distribution update policy below,
--   3. enforce_po_approval_authority(), a trigger that can compare OLD.status to
--      NEW.status — something a with-check expression cannot do.

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type purchase_order_status as enum (
  'draft',
  'pending_finance_approval',
  'approved',
  'ordered',
  'partially_received',
  'received',
  'cancelled'
);

create type dispatch_status as enum (
  'preparing',
  'in_transit',
  'delivered',
  'delayed',
  'cancelled'
);

create type allocation_status as enum ('allocated', 'dispatched', 'returned', 'cancelled');

create type material_return_status as enum ('pending', 'received_by_store', 'rejected');

create type material_condition as enum ('good', 'damaged', 'unusable');

-- ---------------------------------------------------------------------------
-- Tables
--
-- `category` and `unit` are free text rather than enums, matching how Sales
-- models leads.source: the canonical list lives in lib/distribution/constants.ts
-- so adding a material category does not need a migration.
-- ---------------------------------------------------------------------------

create table vendors (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  name            text not null,
  -- 'panels' | 'inverters' | 'structure' | 'cables' | 'accessories' | 'tools' | 'other'
  category        text,
  contact_person  text,
  phone           text,
  email           text,
  address         text,
  gstin           text,
  -- soft delete. A vendor with PO history is never removed, only deactivated.
  is_active       boolean not null default true,
  notes           text,
  created_by      uuid not null references users(id),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index vendors_org_active_idx on vendors (organization_id, is_active);
create index vendors_category_idx   on vendors (category);

create table purchase_orders (
  id                     uuid primary key default gen_random_uuid(),
  organization_id        uuid not null references organizations(id) on delete cascade,
  -- human-readable, e.g. 'PO-2026-0001'. Generated by next_document_number()
  -- below, never by the client.
  po_number              text not null,
  vendor_id              uuid not null references vendors(id),
  status                 purchase_order_status not null default 'draft',
  expected_delivery_date date,
  -- Denormalized for fast list display. Maintained solely by the
  -- recompute_po_total() trigger on purchase_order_items — application code must
  -- never write this column, or it will drift from the line items.
  total_amount           numeric(14, 2) not null default 0,
  created_by             uuid not null references users(id),
  -- Finance approval, per the blueprint's workflow: Finance Approval precedes
  -- Distribution dispatch.
  approved_by            uuid references users(id),
  approved_at            timestamptz,
  notes                  text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  -- Backstop behind next_document_number(): even if two concurrent creates ever
  -- raced past the counter, the second would fail loudly rather than duplicate.
  unique (organization_id, po_number)
);

create index purchase_orders_org_status_idx on purchase_orders (organization_id, status);
create index purchase_orders_vendor_idx     on purchase_orders (vendor_id);
create index purchase_orders_expected_idx   on purchase_orders (expected_delivery_date);

create table purchase_order_items (
  id                uuid primary key default gen_random_uuid(),
  purchase_order_id uuid not null references purchase_orders(id) on delete cascade,
  item_name         text not null,
  category          text,
  quantity          numeric(12, 2) not null,
  unit              text not null default 'nos',
  unit_price        numeric(14, 2) not null,
  line_total        numeric(14, 2) generated always as (quantity * unit_price) stored,
  created_at        timestamptz not null default now(),
  constraint purchase_order_items_quantity_positive check (quantity > 0),
  constraint purchase_order_items_price_nonneg     check (unit_price >= 0)
);

create index purchase_order_items_po_idx on purchase_order_items (purchase_order_id);

create table material_dispatches (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  -- e.g. 'DSP-2026-0001'. Same generator as po_number.
  dispatch_number text not null,
  -- The project this material is going to. Nullable: an internal or
  -- inter-warehouse transfer has no customer lead behind it.
  lead_id         uuid references leads(id) on delete set null,
  dispatched_by   uuid not null references users(id),
  vehicle_details text,
  driver_contact  text,
  status          dispatch_status not null default 'preparing',
  dispatched_at   timestamptz,
  delivered_at    timestamptz,
  delivery_notes  text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (organization_id, dispatch_number)
);

create index material_dispatches_org_status_idx on material_dispatches (organization_id, status);
create index material_dispatches_lead_idx       on material_dispatches (lead_id);
create index material_dispatches_dispatched_idx on material_dispatches (dispatched_at desc);

create table material_dispatch_items (
  id          uuid primary key default gen_random_uuid(),
  dispatch_id uuid not null references material_dispatches(id) on delete cascade,
  item_name   text not null,
  category    text,
  quantity    numeric(12, 2) not null,
  unit        text not null default 'nos',
  created_at  timestamptz not null default now(),
  constraint material_dispatch_items_quantity_positive check (quantity > 0)
);

create index material_dispatch_items_dispatch_idx on material_dispatch_items (dispatch_id);

-- Distribution's plan/commitment record: "this material is going to this
-- project." Deliberately decoupled from any live stock count — Store owns the
-- master inventory and its module does not exist yet, so there is nothing here
-- validating availability against a real balance.
create table material_allocations (
  id                 uuid primary key default gen_random_uuid(),
  organization_id    uuid not null references organizations(id) on delete cascade,
  lead_id            uuid not null references leads(id) on delete cascade,
  item_name          text not null,
  category           text,
  quantity           numeric(12, 2) not null,
  unit               text not null default 'nos',
  allocated_by       uuid not null references users(id),
  status             allocation_status not null default 'allocated',
  -- Set when this allocation actually goes out, by
  -- create_dispatch_from_allocations().
  linked_dispatch_id uuid references material_dispatches(id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint material_allocations_quantity_positive check (quantity > 0)
);

create index material_allocations_org_status_idx on material_allocations (organization_id, status);
create index material_allocations_lead_idx       on material_allocations (lead_id);
create index material_allocations_dispatch_idx   on material_allocations (linked_dispatch_id);

create table material_returns (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  -- Nullable: a return usually references the dispatch it came back from, but
  -- may be logged standalone.
  dispatch_id     uuid references material_dispatches(id) on delete set null,
  lead_id         uuid references leads(id) on delete set null,
  item_name       text not null,
  category        text,
  quantity        numeric(12, 2) not null,
  unit            text not null default 'nos',
  -- 'excess_material' | 'damaged' | 'wrong_item' | 'project_cancelled' | 'other'
  reason          text,
  condition       material_condition not null default 'good',
  returned_by     uuid not null references users(id),
  status          material_return_status not null default 'pending',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint material_returns_quantity_positive check (quantity > 0)
);

create index material_returns_org_status_idx on material_returns (organization_id, status);
create index material_returns_dispatch_idx   on material_returns (dispatch_id);
create index material_returns_lead_idx       on material_returns (lead_id);

-- ---------------------------------------------------------------------------
-- Document numbering
--
-- A counter row per (org, type, year). `on conflict do update ... returning`
-- takes a row lock, so two concurrent creates serialize and cannot be handed the
-- same number — which is what the count(*) + 1 approach would do under
-- concurrency. The unique constraints above are the second line of defence.
-- ---------------------------------------------------------------------------

create table document_counters (
  organization_id uuid not null references organizations(id) on delete cascade,
  -- 'PO' | 'DSP'
  doc_type        text not null,
  year            int  not null,
  last_value      int  not null default 0,
  primary key (organization_id, doc_type, year)
);

create or replace function next_document_number(p_org_id uuid, p_doc_type text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year int := extract(year from now())::int;
  v_seq  int;
begin
  insert into document_counters (organization_id, doc_type, year, last_value)
  values (p_org_id, p_doc_type, v_year, 1)
  on conflict (organization_id, doc_type, year)
  do update set last_value = document_counters.last_value + 1
  returning last_value into v_seq;

  return p_doc_type || '-' || v_year::text || '-' || lpad(v_seq::text, 4, '0');
end;
$$;

-- ---------------------------------------------------------------------------
-- total_amount recompute
--
-- Lives in the database, not application code, so the denormalized total can
-- never drift from the line items — whatever path writes an item, this runs.
-- ---------------------------------------------------------------------------

create or replace function recompute_po_total()
returns trigger
language plpgsql
as $$
declare
  v_po_id uuid := coalesce(new.purchase_order_id, old.purchase_order_id);
begin
  update purchase_orders
     set total_amount = coalesce(
           (select sum(line_total) from purchase_order_items
             where purchase_order_id = v_po_id), 0)
   where id = v_po_id;

  return null;
end;
$$;

-- after-trigger on all three verbs: an edit that deletes a line has to lower the
-- total just as much as one that adds a line raises it.
create trigger recompute_po_total_on_items
  after insert or update or delete on purchase_order_items
  for each row execute function recompute_po_total();

-- ---------------------------------------------------------------------------
-- updated_at triggers (reuses set_updated_at() from 0001)
--
-- purchase_order_items, material_dispatch_items and document_counters have no
-- updated_at column: a line item is replaced rather than revised, and a counter
-- has nothing to timestamp.
-- ---------------------------------------------------------------------------

create trigger set_updated_at_vendors
  before update on vendors
  for each row execute function set_updated_at();

create trigger set_updated_at_purchase_orders
  before update on purchase_orders
  for each row execute function set_updated_at();

create trigger set_updated_at_material_dispatches
  before update on material_dispatches
  for each row execute function set_updated_at();

create trigger set_updated_at_material_allocations
  before update on material_allocations
  for each row execute function set_updated_at();

create trigger set_updated_at_material_returns
  before update on material_returns
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- Membership helpers
--
-- security definer + fixed search_path, matching auth_is_ceo() in 0001 and
-- auth_is_tender_member() in 0003, so the policies below can read
-- users/departments without recursing through their own RLS.
-- ---------------------------------------------------------------------------

create or replace function auth_is_distribution_member()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from users u
    join departments d on d.id = u.department_id
    where u.id = auth.uid() and u.is_active and d.slug = 'distribution'
  );
$$;

-- Finance's only role in this module: approving purchase orders. Accounts is a
-- child department of Finance in the 0002 seed, so it is included — an Accounts
-- user is Finance for approval purposes.
create or replace function auth_is_finance_member()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from users u
    join departments d on d.id = u.department_id
    left join departments parent on parent.id = d.parent_department_id
    where u.id = auth.uid() and u.is_active
      and (d.slug in ('finance', 'accounts') or parent.slug = 'finance')
  );
$$;

create or replace function auth_is_sales_member_dist()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from users u
    join departments d on d.id = u.department_id
    where u.id = auth.uid() and u.is_active and d.slug = 'sales'
  );
$$;

-- ---------------------------------------------------------------------------
-- Finance approval authority
--
-- A with-check expression only sees the proposed row, so it cannot tell an
-- approval apart from a PO that was already approved. This trigger can: it
-- compares OLD.status to NEW.status and refuses the transition into 'approved'
-- unless the caller is Finance or the CEO.
--
-- It also stamps approved_by/approved_at rather than trusting the caller, and
-- clears them if a PO is ever pushed back to a pre-approval state, so those
-- columns cannot claim an approval that did not happen.
-- ---------------------------------------------------------------------------

create or replace function enforce_po_approval_authority()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'approved' and old.status <> 'approved' then
    if not (auth_is_finance_member() or auth_is_ceo()) then
      raise exception 'Only Finance or the CEO can approve a purchase order'
        using errcode = 'check_violation';
    end if;

    new.approved_by := coalesce(auth.uid(), new.approved_by);
    new.approved_at := now();
  end if;

  -- Rolling back to draft or re-review drops the approval stamp with it.
  if new.status in ('draft', 'pending_finance_approval') then
    new.approved_by := null;
    new.approved_at := null;
  end if;

  return new;
end;
$$;

create trigger enforce_po_approval_authority_trg
  before update on purchase_orders
  for each row execute function enforce_po_approval_authority();

-- ---------------------------------------------------------------------------
-- RLS
--
-- Enabling RLS with no matching policy = deny. Multiple permissive policies on
-- one table are OR'd, which is how the tiers compose.
-- ---------------------------------------------------------------------------

alter table vendors                enable row level security;
alter table purchase_orders        enable row level security;
alter table purchase_order_items   enable row level security;
alter table material_dispatches    enable row level security;
alter table material_dispatch_items enable row level security;
alter table material_allocations   enable row level security;
alter table material_returns       enable row level security;
alter table document_counters      enable row level security;

-- vendors -------------------------------------------------------------------

create policy "ceo_full_access_vendors" on vendors
  for all
  using (auth_is_ceo() and organization_id = auth_org_id())
  with check (auth_is_ceo() and organization_id = auth_org_id());

create policy "distribution_dept_access_vendors" on vendors
  for all
  using (auth_is_distribution_member() and organization_id = auth_org_id())
  with check (auth_is_distribution_member() and organization_id = auth_org_id());

-- purchase_orders -----------------------------------------------------------
-- Distribution's access is split by verb rather than granted `for all`: the
-- update policy exists so enforce_po_approval_authority() has something to
-- guard, and Finance gets update-only so it can approve without being able to
-- create or delete Distribution's paperwork.

create policy "ceo_full_access_purchase_orders" on purchase_orders
  for all
  using (auth_is_ceo() and organization_id = auth_org_id())
  with check (auth_is_ceo() and organization_id = auth_org_id());

create policy "distribution_view_purchase_orders" on purchase_orders
  for select
  using (auth_is_distribution_member() and organization_id = auth_org_id());

create policy "distribution_create_purchase_orders" on purchase_orders
  for insert
  with check (
    auth_is_distribution_member()
    and organization_id = auth_org_id()
    -- A PO cannot be born approved. Reaching 'approved' is an update, which is
    -- what the authority trigger inspects.
    and status in ('draft', 'pending_finance_approval')
  );

create policy "distribution_update_purchase_orders" on purchase_orders
  for update
  using (auth_is_distribution_member() and organization_id = auth_org_id())
  with check (auth_is_distribution_member() and organization_id = auth_org_id());

create policy "distribution_delete_purchase_orders" on purchase_orders
  for delete
  using (auth_is_distribution_member() and organization_id = auth_org_id());

-- Finance sees POs awaiting them and may act on them. Update-only: approving is
-- the whole of Finance's business here.
create policy "finance_view_purchase_orders" on purchase_orders
  for select
  using (auth_is_finance_member() and organization_id = auth_org_id());

create policy "finance_approve_purchase_orders" on purchase_orders
  for update
  using (auth_is_finance_member() and organization_id = auth_org_id())
  with check (auth_is_finance_member() and organization_id = auth_org_id());

-- purchase_order_items ------------------------------------------------------
-- Scoped through the parent PO, which already enforces the org check.

create policy "ceo_full_access_po_items" on purchase_order_items
  for all
  using (auth_is_ceo() and exists (
    select 1 from purchase_orders po
    where po.id = purchase_order_items.purchase_order_id
      and po.organization_id = auth_org_id()))
  with check (auth_is_ceo() and exists (
    select 1 from purchase_orders po
    where po.id = purchase_order_items.purchase_order_id
      and po.organization_id = auth_org_id()));

create policy "distribution_dept_access_po_items" on purchase_order_items
  for all
  using (auth_is_distribution_member() and exists (
    select 1 from purchase_orders po
    where po.id = purchase_order_items.purchase_order_id
      and po.organization_id = auth_org_id()))
  with check (auth_is_distribution_member() and exists (
    select 1 from purchase_orders po
    where po.id = purchase_order_items.purchase_order_id
      and po.organization_id = auth_org_id()));

-- Finance reads the line items behind a PO it is being asked to approve.
create policy "finance_view_po_items" on purchase_order_items
  for select
  using (auth_is_finance_member() and exists (
    select 1 from purchase_orders po
    where po.id = purchase_order_items.purchase_order_id
      and po.organization_id = auth_org_id()));

-- material_dispatches -------------------------------------------------------

create policy "ceo_full_access_material_dispatches" on material_dispatches
  for all
  using (auth_is_ceo() and organization_id = auth_org_id())
  with check (auth_is_ceo() and organization_id = auth_org_id());

create policy "distribution_dept_access_material_dispatches" on material_dispatches
  for all
  using (auth_is_distribution_member() and organization_id = auth_org_id())
  with check (auth_is_distribution_member() and organization_id = auth_org_id());

-- The one cross-department read in this module: a Sales employee can see whether
-- material has gone out for a lead assigned to them. Select only, and only for
-- their own leads — deliberately not extended to vendors, POs, or returns, which
-- are Distribution's internal business.
create policy "sales_read_own_lead_dispatches" on material_dispatches
  for select
  using (
    auth_is_sales_member_dist()
    and organization_id = auth_org_id()
    and exists (
      select 1 from leads l
      where l.id = material_dispatches.lead_id
        and l.assigned_to = auth.uid()
    )
  );

-- material_dispatch_items ---------------------------------------------------

create policy "ceo_full_access_dispatch_items" on material_dispatch_items
  for all
  using (auth_is_ceo() and exists (
    select 1 from material_dispatches d
    where d.id = material_dispatch_items.dispatch_id
      and d.organization_id = auth_org_id()))
  with check (auth_is_ceo() and exists (
    select 1 from material_dispatches d
    where d.id = material_dispatch_items.dispatch_id
      and d.organization_id = auth_org_id()));

create policy "distribution_dept_access_dispatch_items" on material_dispatch_items
  for all
  using (auth_is_distribution_member() and exists (
    select 1 from material_dispatches d
    where d.id = material_dispatch_items.dispatch_id
      and d.organization_id = auth_org_id()))
  with check (auth_is_distribution_member() and exists (
    select 1 from material_dispatches d
    where d.id = material_dispatch_items.dispatch_id
      and d.organization_id = auth_org_id()));

-- Sales sees what was sent for their own lead, matching the dispatch read above.
create policy "sales_read_own_lead_dispatch_items" on material_dispatch_items
  for select
  using (
    auth_is_sales_member_dist()
    and exists (
      select 1 from material_dispatches d
      join leads l on l.id = d.lead_id
      where d.id = material_dispatch_items.dispatch_id
        and d.organization_id = auth_org_id()
        and l.assigned_to = auth.uid()
    )
  );

-- material_allocations ------------------------------------------------------

create policy "ceo_full_access_material_allocations" on material_allocations
  for all
  using (auth_is_ceo() and organization_id = auth_org_id())
  with check (auth_is_ceo() and organization_id = auth_org_id());

create policy "distribution_dept_access_material_allocations" on material_allocations
  for all
  using (auth_is_distribution_member() and organization_id = auth_org_id())
  with check (auth_is_distribution_member() and organization_id = auth_org_id());

create policy "sales_read_own_lead_allocations" on material_allocations
  for select
  using (
    auth_is_sales_member_dist()
    and organization_id = auth_org_id()
    and exists (
      select 1 from leads l
      where l.id = material_allocations.lead_id
        and l.assigned_to = auth.uid()
    )
  );

-- material_returns ----------------------------------------------------------
-- No Sales read here on purpose: a return is Distribution and Store's business.

create policy "ceo_full_access_material_returns" on material_returns
  for all
  using (auth_is_ceo() and organization_id = auth_org_id())
  with check (auth_is_ceo() and organization_id = auth_org_id());

create policy "distribution_dept_access_material_returns" on material_returns
  for all
  using (auth_is_distribution_member() and organization_id = auth_org_id())
  with check (auth_is_distribution_member() and organization_id = auth_org_id());

-- document_counters ---------------------------------------------------------
-- No policy at all, so every direct read and write is denied. The only way in is
-- next_document_number(), which is security definer — nobody hand-edits a
-- counter and reissues a PO number that already exists on paper.

-- ---------------------------------------------------------------------------
-- The reverse cross-department read: Distribution needs to see the projects it
-- is moving material for.
--
-- Not in the build spec, but the module cannot work without it. Allocations and
-- dispatches carry a lead_id, the allocation board groups by project, and the
-- dispatch form needs a project picker — and migration 0005 grants `leads` reads
-- to the CEO, Sales managers, and a lead's own assignee only. Without this, every
-- project name in this module renders blank and the picker is empty.
--
-- Deliberately narrow in both directions:
--   * select only — Distribution never writes to the Sales pipeline;
--   * 'won' rows only — a won lead is a live project with material to move. The
--     open pipeline is Sales' business and Distribution has no reason to see a
--     lead that has not been closed, so this is not a window onto the funnel.
-- ---------------------------------------------------------------------------

create policy "distribution_read_won_leads" on leads
  for select
  using (
    auth_is_distribution_member()
    and organization_id = auth_org_id()
    and status = 'won'
  );

-- ---------------------------------------------------------------------------
-- create_purchase_order(): PO + line items in one statement
--
-- One call rather than an insert followed by N item inserts: a client-side
-- sequence could fail partway and leave a PO with half its lines, and its
-- total_amount would then be a real number that happens to be wrong.
--
-- Not security definer — it runs as the caller, so every write inside still
-- passes RLS. The numbering call inside it is security definer because
-- document_counters denies everyone.
-- ---------------------------------------------------------------------------

create or replace function create_purchase_order(
  p_vendor_id     uuid,
  p_items         jsonb,
  p_expected_date date default null,
  p_notes         text default null,
  p_submit        boolean default false
)
returns uuid
language plpgsql
as $$
declare
  v_org_id uuid := auth_org_id();
  v_po_id  uuid;
  v_item   jsonb;
  v_count  int  := 0;
begin
  if v_org_id is null then
    raise exception 'No organization for the current user';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A purchase order needs at least one line item';
  end if;

  -- RLS decides visibility: a vendor outside the caller's org yields no row.
  if not exists (
    select 1 from vendors v
    where v.id = p_vendor_id and v.organization_id = v_org_id and v.is_active
  ) then
    raise exception 'Vendor not found or inactive';
  end if;

  insert into purchase_orders (
    organization_id, po_number, vendor_id, status,
    expected_delivery_date, created_by, notes
  )
  values (
    v_org_id,
    next_document_number(v_org_id, 'PO'),
    p_vendor_id,
    case when p_submit then 'pending_finance_approval'::purchase_order_status
         else 'draft'::purchase_order_status end,
    p_expected_date,
    auth.uid(),
    p_notes
  )
  returning id into v_po_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into purchase_order_items (
      purchase_order_id, item_name, category, quantity, unit, unit_price
    )
    values (
      v_po_id,
      v_item->>'item_name',
      nullif(v_item->>'category', ''),
      (v_item->>'quantity')::numeric,
      coalesce(nullif(v_item->>'unit', ''), 'nos'),
      (v_item->>'unit_price')::numeric
    );
    v_count := v_count + 1;
  end loop;

  -- total_amount is now set by the recompute trigger, not by this function.
  return v_po_id;
end;
$$;

revoke execute on function create_purchase_order(uuid, jsonb, date, text, boolean) from anon;

-- ---------------------------------------------------------------------------
-- replace_purchase_order_items(): swap a draft PO's whole line-item set
--
-- Editing lines means deleting the old ones and inserting the new. Split across
-- two client calls, a failure between them leaves the PO with no lines at all —
-- and total_amount recomputed to 0, which is self-consistent but wrong. One
-- statement makes the swap all-or-nothing.
--
-- The draft check is repeated here rather than trusted from the caller: once
-- Finance has been asked to approve an amount, the lines behind that amount must
-- not move under them.
-- ---------------------------------------------------------------------------

create or replace function replace_purchase_order_items(p_po_id uuid, p_items jsonb)
returns void
language plpgsql
as $$
declare
  v_status purchase_order_status;
  v_item   jsonb;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'A purchase order needs at least one line item';
  end if;

  -- RLS applies: a PO the caller cannot see yields no row and the same error as
  -- one that does not exist.
  select status into v_status from purchase_orders where id = p_po_id for update;
  if not found then
    raise exception 'Purchase order not found';
  end if;

  if v_status <> 'draft' then
    raise exception 'Line items can only be edited while the purchase order is a draft';
  end if;

  delete from purchase_order_items where purchase_order_id = p_po_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into purchase_order_items (
      purchase_order_id, item_name, category, quantity, unit, unit_price
    )
    values (
      p_po_id,
      v_item->>'item_name',
      nullif(v_item->>'category', ''),
      (v_item->>'quantity')::numeric,
      coalesce(nullif(v_item->>'unit', ''), 'nos'),
      (v_item->>'unit_price')::numeric
    );
  end loop;
end;
$$;

revoke execute on function replace_purchase_order_items(uuid, jsonb) from anon;

-- ---------------------------------------------------------------------------
-- Releasing allocations when a dispatch is cancelled
--
-- create_dispatch_from_allocations() moves allocations to 'dispatched' and points
-- them at the new dispatch. If that dispatch is then cancelled, those rows would
-- otherwise sit at 'dispatched' forever, pointing at something that never went
-- out — and since ALLOCATION_TRANSITIONS has no edge back to 'allocated', the
-- material would be permanently un-dispatchable.
--
-- Handled in the database for the same reason as total_amount: the invariant then
-- holds no matter which path cancels the dispatch.
-- ---------------------------------------------------------------------------

create or replace function release_allocations_on_dispatch_cancel()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'cancelled' and old.status <> 'cancelled' then
    -- Scoped by linked_dispatch_id, so this only ever touches allocations that
    -- pointed at this dispatch — already org-bounded by the dispatch row itself.
    -- Only 'dispatched' rows are released: one already marked 'returned' has a
    -- return record behind it and is not this trigger's business.
    update material_allocations
       set status = 'allocated', linked_dispatch_id = null
     where linked_dispatch_id = new.id
       and status = 'dispatched';
  end if;

  return null;
end;
$$;

create trigger release_allocations_on_dispatch_cancel_trg
  after update on material_dispatches
  for each row execute function release_allocations_on_dispatch_cancel();

-- ---------------------------------------------------------------------------
-- create_dispatch_from_allocations(): dispatch + items + allocation updates
--
-- The atomicity requirement in this module. Creating a dispatch out of planned
-- allocations touches three tables, and a partial failure would leave either a
-- dispatch whose allocations still read 'allocated' (so the same material gets
-- sent twice) or allocations marked 'dispatched' pointing at nothing. One
-- statement makes both impossible.
--
-- p_allocation_ids may be empty, which is the ad-hoc dispatch case: items come
-- straight from p_items instead.
-- ---------------------------------------------------------------------------

create or replace function create_dispatch_from_allocations(
  p_lead_id         uuid default null,
  p_allocation_ids  uuid[] default '{}',
  p_items           jsonb default '[]',
  p_vehicle_details text default null,
  p_driver_contact  text default null,
  p_notes           text default null
)
returns uuid
language plpgsql
as $$
declare
  v_org_id      uuid := auth_org_id();
  v_dispatch_id uuid;
  v_item        jsonb;
  v_alloc       record;
  v_item_count  int := 0;
begin
  if v_org_id is null then
    raise exception 'No organization for the current user';
  end if;

  insert into material_dispatches (
    organization_id, dispatch_number, lead_id, dispatched_by,
    vehicle_details, driver_contact, status, delivery_notes
  )
  values (
    v_org_id,
    next_document_number(v_org_id, 'DSP'),
    p_lead_id,
    auth.uid(),
    p_vehicle_details,
    p_driver_contact,
    'preparing',
    p_notes
  )
  returning id into v_dispatch_id;

  -- Allocation-sourced items. `for update` locks each allocation row, so two
  -- dispatches cannot claim the same allocation concurrently.
  if array_length(p_allocation_ids, 1) > 0 then
    for v_alloc in
      select * from material_allocations
      where id = any(p_allocation_ids)
        and organization_id = v_org_id
      for update
    loop
      if v_alloc.status <> 'allocated' then
        raise exception 'Allocation for % is already %', v_alloc.item_name, v_alloc.status;
      end if;

      -- A dispatch drawn from allocations must go to the project they were
      -- earmarked for, or the plan record stops meaning anything.
      if p_lead_id is not null and v_alloc.lead_id <> p_lead_id then
        raise exception 'Allocation for % belongs to a different project', v_alloc.item_name;
      end if;

      insert into material_dispatch_items (dispatch_id, item_name, category, quantity, unit)
      values (v_dispatch_id, v_alloc.item_name, v_alloc.category, v_alloc.quantity, v_alloc.unit);

      update material_allocations
         set status = 'dispatched', linked_dispatch_id = v_dispatch_id
       where id = v_alloc.id;

      v_item_count := v_item_count + 1;
    end loop;

    -- Fewer rows touched than ids passed means at least one was invisible to
    -- this caller or outside their org. Fail rather than silently short-ship.
    if v_item_count <> array_length(p_allocation_ids, 1) then
      raise exception 'One or more allocations could not be found';
    end if;
  end if;

  -- Ad-hoc items, added alongside or instead of allocations.
  if p_items is not null and jsonb_typeof(p_items) = 'array' then
    for v_item in select * from jsonb_array_elements(p_items)
    loop
      insert into material_dispatch_items (dispatch_id, item_name, category, quantity, unit)
      values (
        v_dispatch_id,
        v_item->>'item_name',
        nullif(v_item->>'category', ''),
        (v_item->>'quantity')::numeric,
        coalesce(nullif(v_item->>'unit', ''), 'nos')
      );
      v_item_count := v_item_count + 1;
    end loop;
  end if;

  if v_item_count = 0 then
    raise exception 'A dispatch needs at least one item';
  end if;

  return v_dispatch_id;
end;
$$;

revoke execute on function create_dispatch_from_allocations(uuid, uuid[], jsonb, text, text, text) from anon;

-- ---------------------------------------------------------------------------
-- Seed: Distribution Manager role + module permissions
--
-- 0002 seeds only CEO and '<Department> Executive'. The Distribution module has
-- no manager-only behaviour of its own — the tiers here are CEO and department —
-- but the role is seeded so the '<Department> Manager' convention that
-- isDepartmentManager() and auth_is_department_manager() rely on holds for
-- Distribution too, and so CEO-assigned department tasks have someone to
-- delegate them.
-- ---------------------------------------------------------------------------

do $$
declare
  org_id       uuid;
  dist_dept_id uuid;
  mgr_role_id  uuid;
  exec_role_id uuid;
begin
  select id into org_id from organizations where name = 'Solar Pulse';
  if org_id is null then return; end if;

  select id into dist_dept_id
    from departments
   where organization_id = org_id and slug = 'distribution';
  if dist_dept_id is null then return; end if;

  select id into mgr_role_id
    from roles
   where organization_id = org_id and name = 'Distribution Manager';

  if mgr_role_id is null then
    insert into roles (organization_id, department_id, name)
    values (org_id, dist_dept_id, 'Distribution Manager')
    returning id into mgr_role_id;
  end if;

  insert into permissions (role_id, module, can_view, can_create, can_edit, can_delete, can_approve, can_export)
  select mgr_role_id, m, true, true, true, false, false, true
  from unnest(array['tasks','approvals','departments','vendors','purchase_orders','dispatches','allocations','returns']) as m
  on conflict (role_id, module) do nothing;

  select id into exec_role_id
    from roles
   where organization_id = org_id and name = 'Distribution Executive';

  if exec_role_id is not null then
    insert into permissions (role_id, module, can_view, can_create, can_edit, can_delete, can_approve, can_export)
    select exec_role_id, m, true, true, true, false, false, false
    from unnest(array['vendors','purchase_orders','dispatches','allocations','returns']) as m
    on conflict (role_id, module) do nothing;
  end if;
end;
$$;
